### ISSUE TITLE
Time!

### ISSUE THREAD

**Issue by ttaha** [klutch/UnityGifDecoder#1]
Hello Man, great Job! 
Everything worked perfectly, except that it takes more than 30 seconds to load the scripts ( splash screen) especially on android! do you know why ? 
Thanks!

**Comment by klutch** [comment]
This repo was just an experimental project to get around Unity's (at the time) limitation of not being able to load movie files unless you had the Pro version. On the desktop it worked pretty well, with loading times in the 20-30 second range for converting 3 gifs into an array of textures. On mobile devices, the speed was so bad that I abandoned the whole idea, because it was taking 1-2 minutes to convert. 

I should probably add this info to a README.
